### ISSUE TITLE
Assigning nullable value to non nullable variable - `For key in object`

### ISSUE THREAD

**Issue by Corky3892** [JaroslawPokropinski/eslint-plugin-strict-null-checks#10]
It would appear that this particular message generates erroneously in the case of a `for key in object` pattern. For example:

```typescript
const t = {
   a: 'a'
 };
for (const key in t) {
}
```
![image](https://user-images.githubusercontent.com/23141725/172438614-c3c0da9e-c358-43cf-8b81-1e20b9dfad5b.png)

I do not believe in such cases that a warning should be displayed. This does not generate a TypeScript compiler warning.

**Comment by JaroslawPokropinski** [comment]
Thanks, seems that i forgotten about `for in` when implementing flow for `for of` 🙂
