### ISSUE TITLE
Maximum call stack exceeded error crashing CI pipelines

### ISSUE THREAD

**Issue by DLiblik** [JaroslawPokropinski/eslint-plugin-strict-null-checks#13]
### Scenario

Sometimes TS just can't figure stuff out and this type of statement is the only way 'round:

```ts
// Force the conversion
const smReq = req as unknown as ISmRequest<TParams, TRequest>;
```

### Issue

Unfortunately this causes an infinite recursion in `compareTypeObjects` here:

https://github.com/JaroslawPokropinski/eslint-plugin-strict-null-checks/blob/main/src/utils/compare.ts#L51

### Workaround

The workaround (for others encountering this) is to alter the function declaration in the above file to add an extra `level` parameter...

```js
function compareTypeObjects(left, right, checker, level) {
```

... and then increment it on each recursion and bail if the level hits a large number (I use 50) - notice that the call to `compareTypeObjects` must be augmented with an increment to `level`:

```ts
//...
        if (level > 50) {
          return true;
        }
        if (!compareTypeObjects(leftPropertyType, rightPropertyType, checker, (level||0)+1))
            return false;
//...
```

**Comment by JaroslawPokropinski** [comment]
Hello, thank you for pointing out the issue. Would you be able to provide a minimal example to reproduce that? I tried 
```
interface ISmRequest<TParams, TRequest> {
    params: TParams;
    request: TRequest;
}
const req = {
    params: 0,
    request: null
};
const smReq = req as unknown as ISmRequest<number, string>;
```
but it does not fail.

**Comment by DLiblik** [comment]
It seems to have gotten into a loop where the `left` parameter cycles between `left.symbol.escapedName` being `Buffer` and `__type`.  This is deep in a project so if you can give me some kind of trace command to spit out some diagnostics at a breakpoint then I can provide more info accordingly.

**Comment by DLiblik** [comment]
I think the issue is that there is no recursion guard here generally.  If fathoming the properties connects to an earlier node, it just keeps going.  Maybe add a stack as a final property to ensure you don't see the same thing twice.
