### ISSUE TITLE
Plugin does not work with functions

### ISSUE THREAD

**Issue by sheppard30** [JaroslawPokropinski/eslint-plugin-strict-null-checks#23]
Hej,

In this case, I assumed plugin should highlight that fn is potentially undefined but it does not.

```
type Fn = (() => void) | undefined;

const boo = (fn?: Fn) => {
	fn();
};

boo();
```

**Comment by JaroslawPokropinski** [comment]
Hi, I made a pretty big change in the code lately where errors will be read directly from the typescript.
I added this case to unit test so it should work now but if you still have any issues please let me know.
