### ISSUE TITLE
Error: Failed to load plugin 'strict-null-checks' declared in '.eslintrc.js': Cannot find module 'typescript'

### ISSUE THREAD

**Issue by cfman** [JaroslawPokropinski/eslint-plugin-strict-null-checks#28]
Using version 0.1.1

Encountered the error `Failed to load plugin 'strict-null-checks' declared in '.eslintrc.js': Cannot find module 'typescript'`

**Comment by JaroslawPokropinski** [comment]
It seems that you do not have the typescript installed as a dependency.
Try `npm install -D typescript`
I'll add typescript as peer dependency in the next release

**Comment by cfman** [comment]
Hi @JaroslawPokropinski , tried the latest version 0.1.2 but the same error remain

After installing typescript myself, I faced another error while running eslint:

`Error: Error while loading rule 'strict-null-checks/all': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.`

But I have already added the parserOptions.project in my eslint config, any idea?

You can have a look at my sample project here https://github.com/cfman/eslint-testing

**Comment by JaroslawPokropinski** [comment]
I see that you are trying to use this plugin on javascript project. The aim of this project is to allow for easier migration of typescript projects to use the typescript "strict" option.
You might be able to achieve your goal by configuring typescript and eslint (https://typescript-eslint.io/getting-started) and maybe setting very lax rules that would allow using js code in ts files (or maybe allow js rule might help)
I am not sure what you are trying to accomplish but this plugin uses typescript package to detect potentially nullable values and mark them so i am not sure that it will work well with js code.

**Comment by cfman** [comment]
Was trying to leverage eslint to do strict null checking in a javascript project. Ok, thanks for your help
