### ISSUE TITLE
"Passing nullable argument to function that expects non-nullable" for an any typed function argument

### ISSUE THREAD

**Issue by hbhrugubanda** [JaroslawPokropinski/eslint-plugin-strict-null-checks#9]
Hi! 

I came across an interesting scenario and was curious whether it was the plugin or typescript.

For the following function, `arg1` shows an eslint error.

![image](https://user-images.githubusercontent.com/8406185/160532163-31e8197f-cc63-4b8b-b64b-f36918e041c1.png)

Looking at the message it says "Passing nullable argument to function that expects non nullable": 

![image](https://user-images.githubusercontent.com/8406185/160532087-a8e46e42-4091-4dd7-8ec3-4a7af0b68cdd.png)

The type definition of Array locally shows that the argument is typed as any `isArray(arg: any): arg is any[];` but it's still flagged as non-nullable. 

Have you come across this before or do you have any hints where I can start looking? Thank you!!

**Comment by JaroslawPokropinski** [comment]
Thank you, it seems that the plugin was not handling the any type. It should be fine in 0.0.16.
